apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/bridge
patches:
  - path: bridge-values.yaml
    target:
      kind: StatefulSet
      labelSelector: app=site1pool1bridge1
