apiVersion: batch/v1
kind: CronJob
metadata:
  name: not-used
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - env:
                - name: LOGLEVEL
                  value: INFO
                - name: SERVERPOD
                  value: "https://cd-near.online.dev.tabint.net/"
                - name: SITE
                  value: "chandreshcdnear1"
              image: 010465704656.dkr.ecr.us-west-2.amazonaws.com/pat_client:0.1.0-1
              name: pat-client
